In [2]:
import torch
torch.__version__

'2.0.1+cpu'

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Get dimensions
scalar.ndim

0

In [5]:
# Get the Python number within a tensor
# (only works with one-element tensors)
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# Check the number of dimensions of vector
vector.ndim

1

In [8]:
# Check shape of vector
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [13]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(2, 2,2))
random_tensor, random_tensor.dtype

(tensor([[[0.3664, 0.8368],
          [0.9587, 0.4367]],
 
         [[0.0905, 0.7833],
          [0.7497, 0.8950]]]),
 torch.float32)

In [15]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor, random_image_size_tensor.ndim

(tensor([[[2.3374e-01, 7.8492e-01, 7.7539e-01],
          [9.8820e-01, 2.5521e-01, 8.1811e-01],
          [4.8516e-01, 2.8911e-01, 2.1643e-01],
          ...,
          [1.7667e-01, 7.3067e-01, 7.9235e-01],
          [7.5614e-01, 8.6795e-01, 5.9593e-01],
          [4.0396e-02, 3.2993e-01, 6.0420e-01]],
 
         [[5.0297e-01, 8.8365e-01, 3.6769e-01],
          [2.6640e-01, 3.8754e-01, 7.2002e-01],
          [2.4217e-01, 5.9499e-01, 9.9852e-01],
          ...,
          [9.0613e-01, 7.3426e-01, 1.6948e-01],
          [1.9571e-01, 4.8579e-02, 3.1020e-01],
          [5.9194e-01, 3.5867e-01, 1.9130e-01]],
 
         [[2.1522e-01, 8.4883e-01, 5.8674e-01],
          [8.8549e-01, 3.4388e-01, 8.5779e-01],
          [8.2630e-01, 5.4662e-02, 8.8044e-01],
          ...,
          [1.4188e-01, 3.6717e-01, 5.0593e-01],
          [9.1194e-01, 6.9970e-01, 8.1581e-04],
          [5.5932e-01, 4.2753e-01, 2.3059e-01]],
 
         ...,
 
         [[6.5229e-01, 5.6130e-01, 6.6879e-01],
          [8.4249e

In [16]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [18]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
ten_zeros = torch.zeros_like(input=zero_to_ten) 
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
# Generally if you see torch.cuda anywhere, the tensor is being used for 
# GPU (since Nvidia GPUs use a computing toolkit called CUDA).

In [21]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))